app = "pocketbase"
version = "0.34.2"
build_command = "echo Building pocketbase..."
distfile = "pocketbase"
release_command = "pocketbase migrate"
installation_mode = "binary"

[webserver]
upstream = "localhost:8090"

[processes]
web = { command = "pocketbase serve --http 0.0.0.0:8090" }

[aliases]
shell = "server exec --appenv bash"

# [host]
# domain_name = "localhost"
# envfile = ".env.prod"
# user = "vagrant"
# key_filename = "../../../.vagrant/machines/default/virtualbox/private_key"
# ssh_port = 2222

[host]
domain_name = "pocket.13.204.64.39.nip.io"
envfile = ".env.prod"
user = "ubuntu"
key_filename = "/var/home/tobi/bluefin.pem"
