app = "pocketbase"
version = "0.34.2"
build_command = "echo Building pocketbase..."
distfile = "pocketbase"
installation_mode = "binary"

[aliases]
shell = "server exec --appenv bash"

[[hosts]]
envfile = ".env.prod"
user = "ubuntu"
key_filename = "/var/home/tobi/bluefin.pem"
address = "pocket.13.204.64.39.nip.io"
